import logging
from typing import Dict, Any

logger = logging.getLogger("vulnstrike")

class ReportGenerator:
    def __init__(self, state: Dict[str, Any], report_file: str):
        self.state = state
        self.report_file = report_file

    def generate(self):
        try:
            with open(self.report_file, 'w', encoding='utf-8') as f:
                f.write(f"# VulnStrike Scan Report\n\n")
                f.write(f"**Target:** {self.state['target']}\n\n")
                
                f.write("## Technologies Detected\n")
                if self.state['technologies']:
                    for t in self.state['technologies']:
                        f.write(f"- {t['tech']} ({t['host']})\n")
                else:
                    f.write("None detected.\n")
                f.write("\n")
                
                f.write("## Possible CVEs\n")
                if self.state['cves']:
                    for c in self.state['cves']:
                        f.write(f"- **{c['cve']}** – {c['description']} ({c['tech']})\n")
                else:
                    f.write("None mapped.\n")
                f.write("\n")
                
                f.write("## Vulnerabilities\n")
                if self.state['vulnerabilities']:
                    # Group by severity
                    vulns = self.state['vulnerabilities']
                    highs = [v for v in vulns if v.get('severity') == 'High']
                    mediums = [v for v in vulns if v.get('severity') == 'Medium']
                    lows = [v for v in vulns if v.get('severity') == 'Low']
                    
                    if highs:
                        f.write("### High\n")
                        for v in highs:
                            f.write(f"- {v['type']} on {v['target']}\n")
                        f.write("\n")
                    if mediums:
                        f.write("### Medium\n")
                        for v in mediums:
                            f.write(f"- {v['type']} on {v['target']}\n")
                        f.write("\n")
                    if lows:
                        f.write("### Low\n")
                        for v in lows:
                            f.write(f"- {v['type']} on {v['target']}\n")
                        f.write("\n")
                else:
                    f.write("None found.\n")
                f.write("\n")
                
                f.write("## Recon Results\n")
                f.write(f"**Subdomains Discovered:** {len(self.state['subdomains'])}\n")
                f.write(f"**Live Hosts:** {len(self.state['live_hosts'])}\n")
                f.write(f"**Endpoints Discovered:** {len(self.state['endpoints'])}\n")
                f.write("\n")
                
                f.write("---\n")
                f.write("Generated by VulnStrike\n\n")
                f.write("Created by syn9 (Ashwani Mishra)\n")
                f.write("GitHub: https://github.com/ashwyni-mishra/vulnstrike\n")
                
            logger.info(f"Report successfully written to {self.report_file}")
        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
